"""Unit tests for nuguard.common.auth.AuthConfig."""
from __future__ import annotations

import base64
import textwrap

import pytest

from nuguard.common.auth import AuthConfig


class TestToHeaders:
    def test_bearer_to_headers(self) -> None:
        cfg = AuthConfig(type="bearer", header="Authorization: Bearer tok")
        assert cfg.to_headers() == {"Authorization": "Bearer tok"}

    def test_api_key_to_headers(self) -> None:
        cfg = AuthConfig(type="api_key", header="X-API-Key: secret123")
        assert cfg.to_headers() == {"X-API-Key": "secret123"}

    def test_basic_to_headers(self) -> None:
        cfg = AuthConfig(type="basic", username="alice", password="p@ss")
        expected = base64.b64encode(b"alice:p@ss").decode()
        assert cfg.to_headers() == {"Authorization": f"Basic {expected}"}

    def test_none_to_headers(self) -> None:
        cfg = AuthConfig(type="none")
        assert cfg.to_headers() == {}


class TestFromHeaderString:
    def test_bearer(self) -> None:
        cfg = AuthConfig.from_header_string("Authorization: Bearer mytoken")
        assert cfg.type == "bearer"
        assert cfg.header == "Authorization: Bearer mytoken"

    def test_api_key(self) -> None:
        cfg = AuthConfig.from_header_string("X-API-Key: secret")
        assert cfg.type == "api_key"
        assert cfg.header == "X-API-Key: secret"

    def test_empty_string_returns_none(self) -> None:
        cfg = AuthConfig.from_header_string("")
        assert cfg.type == "none"

    def test_whitespace_only_returns_none(self) -> None:
        cfg = AuthConfig.from_header_string("   ")
        assert cfg.type == "none"


class TestFromTenantToken:
    def test_bare_token_becomes_bearer(self) -> None:
        cfg = AuthConfig.from_tenant_token("tok_abc123")
        assert cfg.type == "bearer"
        assert cfg.header == "Authorization: Bearer tok_abc123"

    def test_header_string_preserved(self) -> None:
        cfg = AuthConfig.from_tenant_token("X-API-Key: sk-tenant-001")
        assert cfg.type == "api_key"
        assert cfg.header == "X-API-Key: sk-tenant-001"

    def test_empty_token_returns_none(self) -> None:
        cfg = AuthConfig.from_tenant_token("")
        assert cfg.type == "none"


class TestValidation:
    def test_bearer_missing_header_raises(self) -> None:
        with pytest.raises(ValueError, match="auth.type=bearer requires auth.header"):
            AuthConfig(type="bearer")

    def test_api_key_missing_header_raises(self) -> None:
        with pytest.raises(ValueError, match="auth.type=api_key requires auth.header"):
            AuthConfig(type="api_key")

    def test_basic_missing_password_raises(self) -> None:
        with pytest.raises(ValueError, match="auth.type=basic requires"):
            AuthConfig(type="basic", username="alice")

    def test_basic_missing_username_raises(self) -> None:
        with pytest.raises(ValueError, match="auth.type=basic requires"):
            AuthConfig(type="basic", password="pass")

    def test_cookie_file_empty_path_raises(self) -> None:
        with pytest.raises(ValueError, match="auth.type=cookie_file requires auth.cookie_file"):
            AuthConfig(type="cookie_file")

    def test_cookie_file_valid_construction(self, tmp_path: "pytest.TempPathFactory") -> None:
        cookies_file = tmp_path / "cookies.txt"
        cookies_file.write_text("# Netscape HTTP Cookie File\n")
        cfg = AuthConfig(type="cookie_file", cookie_file=str(cookies_file))
        assert cfg.type == "cookie_file"
        assert cfg.cookie_file == str(cookies_file)


_NETSCAPE_COOKIES = textwrap.dedent("""\
    # Netscape HTTP Cookie File
    # Generated by curl

    .example.com\tTRUE\t/\tFALSE\t1999999999\tsession\tabc123
    .example.com\tTRUE\t/\tTRUE\t1999999999\tcsrf\txyz789
""")


class TestCookieFileToHeaders:
    def test_valid_cookies_txt(self, tmp_path: "pytest.TempPathFactory") -> None:
        cookies_file = tmp_path / "cookies.txt"
        cookies_file.write_text(_NETSCAPE_COOKIES)
        cfg = AuthConfig(type="cookie_file", cookie_file=str(cookies_file))
        headers = cfg.to_headers()
        assert headers == {"Cookie": "session=abc123; csrf=xyz789"}

    def test_empty_cookies_txt_returns_empty_dict(self, tmp_path: "pytest.TempPathFactory") -> None:
        cookies_file = tmp_path / "cookies.txt"
        cookies_file.write_text("# Netscape HTTP Cookie File\n# only comments\n\n")
        cfg = AuthConfig(type="cookie_file", cookie_file=str(cookies_file))
        assert cfg.to_headers() == {}

    def test_missing_file_raises_file_not_found(self, tmp_path: "pytest.TempPathFactory") -> None:
        missing = tmp_path / "nonexistent_cookies.txt"
        cfg = AuthConfig(type="cookie_file", cookie_file=str(missing))
        with pytest.raises(FileNotFoundError, match="auth.cookie_file: file not found"):
            cfg.to_headers()

    def test_malformed_lines_are_skipped(self, tmp_path: "pytest.TempPathFactory") -> None:
        cookies_file = tmp_path / "cookies.txt"
        cookies_file.write_text(
            "# header\n"
            "not-enough-columns\n"
            ".example.com\tTRUE\t/\tFALSE\t1999999999\ttoken\tmy_token\n"
        )
        cfg = AuthConfig(type="cookie_file", cookie_file=str(cookies_file))
        assert cfg.to_headers() == {"Cookie": "token=my_token"}

    def test_single_cookie(self, tmp_path: "pytest.TempPathFactory") -> None:
        cookies_file = tmp_path / "cookies.txt"
        cookies_file.write_text(
            ".example.com\tTRUE\t/\tFALSE\t1999999999\tauth_token\tsecret_value\n"
        )
        cfg = AuthConfig(type="cookie_file", cookie_file=str(cookies_file))
        assert cfg.to_headers() == {"Cookie": "auth_token=secret_value"}

    def test_httponly_cookie_is_parsed(self, tmp_path: "pytest.TempPathFactory") -> None:
        """curl writes HttpOnly cookies with a #HttpOnly_<domain> prefix — must not be skipped."""
        cookies_file = tmp_path / "cookies.txt"
        cookies_file.write_text(
            "# Netscape HTTP Cookie File\n"
            "# This file was generated by libcurl! Edit at your own risk.\n"
            "\n"
            "#HttpOnly_localhost\tFALSE\t/\tFALSE\t1775618378\tsession_id\tD82pkyuu_secret\n"
        )
        cfg = AuthConfig(type="cookie_file", cookie_file=str(cookies_file))
        assert cfg.to_headers() == {"Cookie": "session_id=D82pkyuu_secret"}
