"""Cross-run disk-backed cache for generated behavior scenarios.

Analogous to ``nuguard.redteam.llm_engine.prompt_cache.PromptCache``.

The cache key is a 16-character SHA-256 prefix of the *stable* serialisation of
the SBOM + policy, so whitespace-only policy edits don't bust the cache.

Cache file: ``<cache_dir>/behavior-scenarios-{key}.json``

Usage::

    cache = BehaviorPromptCache(cache_dir="/path/to/output")
    key = cache.cache_key(sbom, policy)
    scenarios = cache.load(key)
    if scenarios is None:
        scenarios = await build_scenarios(...)
        cache.save(key, scenarios)
"""
from __future__ import annotations

import hashlib
import json
import logging
import pathlib
from typing import TYPE_CHECKING

from nuguard.behavior.models import BehaviorScenario

if TYPE_CHECKING:
    from nuguard.models.policy import CognitivePolicy
    from nuguard.sbom.models import AiSbomDocument

_log = logging.getLogger(__name__)


def _stable_json(obj: object | None) -> str:
    """Stable, whitespace-free JSON serialisation suitable for hashing."""
    if obj is None:
        return ""
    try:
        if hasattr(obj, "model_dump"):
            data = obj.model_dump()
        elif isinstance(obj, dict):
            data = obj
        else:
            return str(obj)
        return json.dumps(data, sort_keys=True, separators=(",", ":"), default=str)
    except Exception:
        return ""


class BehaviorPromptCache:
    """Disk-backed cache for behavior scenario lists generated by LLM calls.

    Args:
        cache_dir: Directory in which cache files are stored.  The directory is
            created automatically on first write.  Pass an empty string or
            ``None`` to disable the cache (all operations become no-ops).
    """

    def __init__(self, cache_dir: str | pathlib.Path | None = None) -> None:
        self._enabled = bool(cache_dir)
        self._dir = pathlib.Path(cache_dir) if cache_dir else pathlib.Path(".")

    def cache_key(
        self,
        sbom: "AiSbomDocument | None",
        policy: "CognitivePolicy | None",
    ) -> str:
        """Return a 16-char hex key derived from the SBOM + policy content."""
        combined = _stable_json(sbom) + _stable_json(policy)
        return hashlib.sha256(combined.encode()).hexdigest()[:16]

    def _path(self, key: str) -> pathlib.Path:
        return self._dir / f"behavior-scenarios-{key}.json"

    def load(self, key: str) -> list[BehaviorScenario] | None:
        """Return cached scenarios, or *None* on cache miss / disabled."""
        if not self._enabled:
            return None
        path = self._path(key)
        if not path.exists():
            _log.debug("BehaviorPromptCache: miss  key=%s", key)
            return None
        try:
            raw = path.read_text(encoding="utf-8")
            data = json.loads(raw)
            scenarios = [BehaviorScenario.model_validate(item) for item in data]
            _log.info(
                "BehaviorPromptCache: hit  key=%s  %d scenarios loaded from %s",
                key, len(scenarios), path,
            )
            return scenarios
        except Exception as exc:
            _log.warning(
                "BehaviorPromptCache: failed to load cache key=%s (%s) — treating as miss",
                key, exc,
            )
            return None

    def save(self, key: str, scenarios: list[BehaviorScenario]) -> None:
        """Persist *scenarios* to disk.  Silent no-op if cache is disabled or write fails."""
        if not self._enabled:
            return
        try:
            self._dir.mkdir(parents=True, exist_ok=True)
            path = self._path(key)
            data = [s.model_dump(mode="json") for s in scenarios]
            path.write_text(json.dumps(data, indent=2), encoding="utf-8")
            _log.info(
                "BehaviorPromptCache: saved  key=%s  %d scenarios → %s",
                key, len(scenarios), path,
            )
        except Exception as exc:
            _log.warning("BehaviorPromptCache: failed to save cache key=%s (%s)", key, exc)
